version: "3.6"

services:
  consul-server1:
    image: hashicorp/consul:1.11.2
    container_name: consul-server1
    restart: always
    volumes:
     - ./consul/server1.json:/consul/config/server1.json:ro
     - ./consul/certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"
  consul-server2:
    image: hashicorp/consul:1.11.2
    container_name: consul-server2
    restart: always
    volumes:
     - ./consul/server2.json:/consul/config/server2.json:ro
     - ./consul/certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"
  consul-server3:
    container_name: consul-server3
    image: hashicorp/consul:1.11.2
    restart: always
    volumes:
     - ./consul/server3.json:/consul/config/server3.json:ro
     - ./consul/certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"
  consul-client:
    image: hashicorp/consul:1.11.2
    restart: always
    volumes:
     - ./consul/client.json:/consul/config/client.json:ro
     - ./consul/certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent"
networks:
  consul:
    driver: bridge